manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: mechwild
      url-base: https://github.com/mechwild
    - name: lesshonor
      url-base: https://github.com/lesshonor
  projects:
    - name: mechwild-zmk-keyboards
      #remote: mechwild
      remote: lesshonor  # Eventually, you'll want to swap this out with mechwild.
      revision: cirque
      clone-depth: 1
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: cirque-input-module
      remote: petejohanson
      revision: main
      clone-depth: 1
    - name: zmk
      remote: zmkfirmware
      revision: pull/2027/merge
      clone-depth: 1
      import: app/west.yml
  self:
    path: config
